# Generated by Django 6.0.7 on 2026-07-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
            ],
            options={
                'verbose_name': '게임 기록',
                'verbose_name_plural': '게임 기록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.game',),
        ),
    ]
