# Generated by Django 6.0.7 on 2026-07-19 13:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='공격자 카드')),
                ('defender_card', models.PositiveSmallIntegerField(blank=True, help_text='방어자가 반격하기 전에는 비어 있다.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='방어자 카드')),
                ('rule', models.CharField(blank=True, choices=[('high', '큰 숫자 승리'), ('low', '작은 숫자 승리')], max_length=10, verbose_name='승리 기준')),
                ('status', models.CharField(choices=[('waiting', '반격 대기'), ('finished', '종료')], default='waiting', max_length=10, verbose_name='상태')),
                ('result', models.CharField(blank=True, choices=[('attacker_win', '공격자 승'), ('defender_win', '방어자 승'), ('draw', '무승부')], max_length=12, verbose_name='결과')),
                ('attacker_delta', models.IntegerField(default=0, verbose_name='공격자 점수 변동')),
                ('defender_delta', models.IntegerField(default=0, verbose_name='방어자 점수 변동')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청 시각')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_attacking', to=settings.AUTH_USER_MODEL, verbose_name='공격자')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_defending', to=settings.AUTH_USER_MODEL, verbose_name='방어자')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('attacker', models.F('defender')), _negated=True), name='game_attacker_ne_defender')],
            },
        ),
    ]
